version: '3.8'

services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - ~/.ssh:/home/node/.ssh:cached
      - ~/.npmrc:/home/node/.npmrc:cached
    command: sleep infinity
    working_dir: /workspaces/react-mobile-file-upload-example/mobile